### ISSUE TITLE
install fails (both on mac and linux)

### ISSUE THREAD

**Issue by ipstone** [HGNC/get-gene-info#1]
Hello,

I tried to install get-gene-info through the install.sh, but installed failed both on mac and Linux:
```
=====Install modules
Passed: Install modules                  =====
Create tmp dir
Passed: Create tmp dir
TESTING get-gene-info.pl
Error: TESTING get-gene-info.pl               =====
```

ideas on potential issues? I installed the cpanminus through conda for the dependencies.

Thanks

**Comment by berkuva** [comment]
Same issue.

**Comment by eudoraleer** [comment]
you could try running the command in the same directory containing the get-gene-info.pl file

**Comment by KrisGray** [comment]
I am looking into this now. I shall have this fixed today

**Comment by KrisGray** [comment]
I have updated the JSON module that is downloaded and made clear in the README that install.sh must be run inside the projects directory. I have tested the project on a Mac version 12.4 and with perl  version 5.16.0 and 5.30.3.

**Comment by KrisGray** [comment]
Sorry for the slow fix
